### ISSUE TITLE
Mandate tooling to use the `workflowsSpec` field to interpret a Workflows Description

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#126]
From @handrews review [feedback ](https://github.com/OAI/sig-workflows/issues/49#issuecomment-1836661780)

> The `workflowsSpec` field SHOULD be used by tooling to interpret the Workflows Description.

> Using a SHOULD here leaves room for tools to do something arbitrarily different. Usually a SHOULD means that there are specific but relatively rare good reasons to disregard it. What are the use cases for disregarding this SHOULD? I am asking because we learned through JSON Schema that not locking down the bootstrapping process for interpreting a document leads to incredibly thorny interoperability problems.

The intention is that tooling MUST use the field and avoid ambiguity.

**Comment by frankkilcommins** [comment]
It's worth noting that OpenAPI has similar wording around `SHOULD`. The registered Media Types for Workflows give certain identifier capabilities too.

**Comment by handrews** [comment]
@frankkilcommins the OAS has quite a few places where it's formal requirements need either tightening (SHOULD to MUST) or clarification (when ought you disgregard this SHOULD, and what happens if you do?)

If the media type is intended to be an alternate source, then the specification ought to unambiguously state their precedence, or the situations in which one or the other MUST to be used.

(hm... I find myself using "ought" a lot to avoid confusing should and SHOULD by accident)

**Comment by frankkilcommins** [comment]
@handrews I'm OK to enforce a `MUST` for this version as I'd prefer not to infer too strongly via the media types until #71 is addressed and the existing entries adjusted (or replaced by new registrations).
