### ISSUE TITLE
Clarity on referencing Components Parameters

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#129]
From @handrews feedback [review](https://github.com/OAI/sig-workflows/issues/49#issuecomment-1836661780):

Regarding parameters, the spec states:

> A list of parameters to pass to an operation or workflow as referenced by operationId, operationRef, or workflowId. If a Reference Object is provided, it MUST link to parameters defined in [components/parameters](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#component-object).

Would that be the Components Object in the _entry_ document or the _current_ document?

**Comment by handrews** [comment]
I'd recommend making it the current document.  That's been [proposed for Discriminator in 3.1.1](https://github.com/OAI/OpenAPI-Specification/pull/2618/files#diff-b92507e7acda65ae00a02236c555cefc68b6fca4661077b84c2fb9ab150e5e17R2705) (although idk whether it can go into 3.1.1 or if it would be 3.2) and its closer to how both Workflows and Moonwalk do whole-document imports.

I feel l like we are overall moving towards a document-as-local-scope model, rather than the Swagger 2.0 view where it was assumed that the resolved graph looked like a single document and therefore you didn't care about the individual document structure.  That view is incompatible with full JSON Schema support anyway, which is another reason to move away from it.
