### ISSUE TITLE
Harden the Runtime Expression section within the spec

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#44]
Review and harden the [runtime expressions](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#runtime-expressions) documentation.

Expressions are use by:
- input values
- parameter values
- output values

Success and Failure Object criteria also uses expressions and in the draft examples there is usage of JSONPath. Should alternative _expression_ references be used here?

Review usage of JSONPath, JSON Pointer and/or determine if any form of custom expressions (like [GitHub action expressions](https://docs.github.com/en/actions/learn-github-actions/expressions)) would be required to meet the needs of the success/failure criteria expressions. Should this then be split from the [runtime expressions](https://github.com/OAI/sig-workflows/blob/main/versions/1.0.0.md#runtime-expressions).

**Comment by YurishoSan** [comment]
As discussed in the weekly meeting when I was present, JSONLogic was brought up as a possible . In my use case I find JSONLogic to be a good inital base for an expression language, but one that requires further refinement still.

For JSONPath, note that it's main use case is to express paths, not logical expressions. This makes it less appealing for this purpose.
Also note that JSONPath in it's current form only allows for ONE function call from a set of predefined functions and only at the end of the expression.
Specifically, if one want's the first element of an array: `somearray[*].first()` then there is no way to address some field in this first element as: `somearray[*].first().name` - this is invalid JSONPath syntax.
And also `somearray[*].keys().first()` is invalid JSONPath syntax because it calls two functions.
