### ISSUE TITLE
Determine engagement/overlap with the CNCF Serverless Workflows initiative

### ISSUE THREAD

**Issue by frankkilcommins** [OAI/sig-workflows#47]
Have conversations and determine viability of collaboration with the Serverless Workflows group which exist within the CNCF.

- https://serverlessworkflow.github.io/
- https://github.com/serverlessworkflow/specification/blob/main/examples/README.md

**Comment by shaisachs** [comment]
Here's my impression of our relationship to the serverless group:

- Our relationship is quite friendly and there's an understanding of shared interest, as evidenced by overlap in the specs.
- We've yet to determine whether or not their spec strictly "contains" ours in the functional sense. Is it possible to do everything one can do with our spec, using the serverless workflows spec? It's not yet clear. Because the serverless workflows spec includes GraphQL APIs, it *is* clear that our spec does not "contain" theirs in the functional sense.
- The serverless workflows spec is primarily concerned with orchestration across APIs, and "serverless" is not a strict requirement for those APIs. The name merely indicates the provenance of the work, since originally the interest in this spec came out of the CNCF Serverless SIG.
- As the spec is being drafted under the auspices of CNCF, the workgroup has access to useful resources, e.g. a Kubecon booth, and as such is a great ally.
- There's perhaps a chance of "merging" our efforts with theirs, but there's no clarity on whether or when that would happen. Specifically, it's possible that we'd release a 1.0 version of our spec without resolving the questions of how our spec relates to theirs and vice versa.

As a matter of "jurisdiction", my proposal is that we consider the specs to have roughly the following areas of concern:
- Serverless Workflows: Indicates how to orchestrates a number of APIs, possibly provided by numerous different providers, to accomplish some task.
- OpenAPI Workflows: Gives an API provider the facility to better document its API(s) by indicating how the resources in those API(s) relate to one another. There is no explicit requirement that the Workflow document should apply only to the APIs provided by a single entity,, but that is the "sweet spot" in terms of utility of the spec. Moreover, while the spec may be used to create SDKs for orchestration across APIs, that is not the primary focus of the spec.

By way of analogy, completely stolen from @earth2marsh , the OpenAPI spec tells API consumers: "here are the ingredients provided by this API!" The OpenAPI Workflows spec is something like a cookbook which tells those consumers: "here is how you might turn those ingredients into a delicious dish!"

**Comment by shaisachs** [comment]
I would propose that we resolve this issue. It seems to me that there is room for OpenAPI Workflows spec to exist alongside Serverless Workflows spec, and for there to be opportunities for collaboration in the future.

**Comment by kevin-postman** [comment]
Agreed.

**Comment by frankkilcommins** [comment]
We've determined as a working group that there's enough grounds and value for the API community for us to proceed with an implementor draft
